language: node_js
node_js:
- '8'
- '9'
- '10'
- '11'
- '12'
deploy:
  provider: npm
  email: romain.dary@gmail.com
  api_key:
    secure: r+5+8VTIhmvcccRjG39SRXChsspbDTztNJ1UK6X+XS9DKOJfxtBceaRWDn0QrhzO5D8OJPTYL17WiMpn2xsE5GN6thcf8EqVkWejJ2TmeZWS4gb/L1cOe8vF0nBYR1DE1/QOonwDxoNfe7bxuseUzn0ok2OqHqD9pXjX7X6kkCJ9MFMf80seDAiKRFwUxsfAYCSWsbA5xnKxCoMABVAcvNEwzVpdgCMyd/yaAd1wY6Ccv1uqi1BfYwei4oCJYjfcBpT7JK/fiCRaxaHihKREGLaFom49hwo3fZg3iSjXnp7QVY33IZmNYleCqIyQjSqIIwH1HIu9j5+sDG9jVuyWXsR3W1mRn/d9TfvgZ/TbFfIwCBKTx2P+e9UGiWYiLQPcWN7BbZijIAkE5d34kM8PYJXBwcQo2V0fEM0wmpWxR3Nl0wdYkTbFKIYaSX14rgpZfvmsAZf+U0HbSKpO3i/2rRJZsfqGvUVbHilhqvsT+waOHeFD3DfmZfVakVCGpHKxWGFsTHkTwyjBkb6TzPZ8HN4Gm8CIppIsZebCgla/QB/mu96Jl9+jJQxCavIdDALd1Bq5cKXCYHCeddXmz1fWhzKqWMYMEn9EylH/Xg/LlSb+sTstPHowA3BxBj8Gh5pmcjGO79rJ7Jmh2LJxFMx5g4C1sMS8Za+UjcrbrKnUlVI=
  on:
    tags: true
    repo: renault-digital/eslint-config
